os:
- linux
language: node_js
node_js:
- 6.10.0
jdk:
- oraclejdk8
sudo: required
cache:
  directories:
  - node
  - $HOME/.gradle
  - $HOME/.yarn-cache
env:
  global:
  - NODE_VERSION=6.10.0
  - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
  - SPRING_JPA_SHOW_SQL=false
  - secure: rI/qmiXvy3I3HKNJXzVoG16WkD+1aT3UhJ6uhP6y0exNvktIUa9JWUeaHaVlaxx7b/D1VTeJJgQDNNmeD2pIlIEnVAGwjfnAtECnn1h0IvtluFxfzAk3HTjTWoqfeTgiZAOG5c2MoeI/ya7QMTmhD0TNZ71JNo7XluRc1mlV/4wFa0+mcUkg3qCriPKu9YvNW5o0SVXJpt8XjpduuaYxS0V1LTuGGGAbQMXtDUqgM/h0Yv8j9onaknkR6+If9LJe8ZhFjt28+IyCoeb+88wZ4/VfxJ5ZTSSvuesJmWCsVVFAP/KYbGEbUf3wAbRP0SspWetOwTcEthdtNkx/FzXJ+AhCDBi1jynTaKrK6yK7B8gXOXxdJrKYrBVYKeVhjzNyLRF2vafUf19ZNWoG3G4sCXMSFtenD+p1mHIdf9PrmFUpEevpDht+f/LGvESJYx4QgniMuHQtGSyPDWszVpkcs+RfyZyEezW/G4Xn0DL2gcX6jmCfpyq08ZKGoPwlMDlFVysC0zNnMayK/gwWAcuq0f6g/my3EcrQmAkv20bIu1OEXQq7Vms4F/r2EpGXktkoHZMzzo4OfM+L5RXdO1Ir5Pcn9GqtL7ywTo2G1iD0lnM1ZHkoPPyNY3xCf1XQi+Z2ChQzAjSQUW6GW/qe8W0c4MsR3uQFLccxVgM6iRJZP4s=
    - secure: "U94F5mB0eZe691r58v+WjuQrZ1X1yyBArUS4VIN7NtP+6lFU6dqSrqpRZKvX3pVCMBkncxXP2pxrS0hnZ6kC397pA5gM57E7y1P4hZFh/zESS4icmcsInNd0lrDelJ/dyRXB3KSngtu6cqjUw+id8cxxbXqJGKoMT03QSYsLkWMV4Oh3kVS0r1EeaeOlr05mrH18S4ztemoYI+01j9lTlFmfN7iIon2Zs/sIw8Q04D3OVxaaQxbBmNMJnHbyfbIZUABClVU13QuOR/AeeogJ3GGEeULJL/9J21dcutJMO705rbC5PV639WqG4dBvD7nMt6Hx6++WurSsGPrNQ66CDkMPBcWuN3hIMU05bNz87Z6CLEBTwZ2eA6HLxA5L0J2s8BBj+l4XwRazgAe2wx/FRuveQrtVxZDLEi3wDO0gO2c6L7cZ7AtiOrRy6UdqoO5qN3RygU/Fz+jkSO7y0b0C9Qf11JQ14G/JR03iUQGGCVl10Cq5e+awfGQSvZ1WYgm1D7Fb1Uv54BeKZmzzMa8Tlw1wpqLy3PoRf++ROH98n2KVVgTv0oGecLw5MbG7VVGOOePDF9I4RobQuZ8rus5LHtDhCZhZbjot5cTq8ur+focrrIciyUaG9QkeKYR4IlLB3+ypHoY4nP2DZevBebUt0nhjdWiAXAIuU0FHiWo13VQ=" # DOCKER_EMAIL
    - secure: "hwsx/WeudPvgdyo6wtB8ZyFoV5ATW806ejy5jnjwoTmCTZ266sFr0TduPaOsXIQe+7v4/aozOebw13aCQcrducBmHhRv0aYh2U9rUHiCQU21AYOq5KRD8FlYPt5ridw3qPGrXmbZnttkaqE+ig6eCdg9+cXLab61FWo+LOey+J+HJbHp2lSABA/l3cY35fs1DkzVQeOxqr/4s0VeHIPwRxQKSMl4aq/UeQkcUE6TXxA7nqU4GgMcHaTvvFqMqTaDuQVnI2mNmCBLBclzNBRnl6j7IFdEZgEtuxBEKiwbeZElgjYWQRUFfHpPE/01WJCCuKbG/FpQarLTzjKIqbWpyI580DKYZ9cqwddJOKOZXUIcFLqkzDkk5uRebl39co7IFc5ecOFSHF/2G8N5hBR7ZsdtKkh410Qt/ApWiUjYfIFLYfB8r31hfHB+1mey/mQL02p83bHKhZWTYH51ZWfPzT4z9hbX9e0kooed9jKOXJm40RAZ44LXNHbSR79yBkRFbXQa7rwVw3OvFIFJQ7VvmLPnfmL+FxH8SaBJWi+izDCaPAqByxCCCzrvdoQL5pNHsQh5At3w7WJtW8DjDABthF4+QdPwCO4vqZNFuiyfS4c419FPZHWpyNmPxZG4HcKl+YfeEyV9qI3zSKLcftBbLWvF6WkBxK2pcLY4QgCqVps=" # DOCKER_USER
    - secure: "YmC3UGh+yL/wdWEDSnjE9ZUyCxA4hawMRgEm6ihoQ0P7rE5IJkpdIbHuH7/517/EAfwHhSFBFPcIlb23gwUfq6r3f0Wj9f/OtC7DRQL+acT1stWeqzq3ihVyMsHQrIfbPW+BKWuvxz3dJfzqNAcuqlpA0jiypS4ynDgH1kSWVoguYNTzUxLagRAljYQpXdcEwmPK/GVDHwz4Pjqfea9iHrKmNaPmrFoYg1NDfG3VXa6pVb36pVvs8g0p1HB2tMYsT6dxKPCVN3fQJ4OnUzfGvtOk0jb0GKGaKFiSggcwr5BdDJSeu/YdtnPT9YWJyj+4ZYgnGMP9PvSQYFbsJgwg8qSWuiqUD5pTydiYyj58npDInd4J/oBMMHO42NW7hLaPz6DCxbTVCzG0xnNx5yHlR2WEMFxvG/JjiIHAWVfpjRXB1bazcsrtip89zglsUkUIVZ2RRvzp35oD+3xrFbHuR/ruUU6ZbWU+gI2wg//O44QwY9ef7uNWPTXPG0aDU/A1uxpbciHZ++3we64+36kjvnI3XYLxgu0zgjp/OUAXFHydgi28/h4MbOGyygQdYSLwTFfEsIrutjDZD6aeavzTXgkX5nM8jW40cdf10xP9sOGNNKuQ9LNLNejDG3JX6DY58TFsKR5CyuJqLYU4IO0mCPU0Zz9memrnvwrO15wesP0=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}
before_install:
- jdk_switcher use oraclejdk8
- java -version
- sudo /etc/init.d/mysql stop
- sudo /etc/init.d/postgresql stop
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn install
script:
- chmod +x gradlew
- ./gradlew clean test
- yarn test
- ./gradlew bootRepackage -Pprod -x test
- ./gradlew deployHeroku
after_success:
  - mkdir -p ./build/docker && cp ./src/main/docker/* ./build/docker && cp ./build/libs/* ./build/docker
  - cd ./build/docker/
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=kmcdonald/opengive-denver-2017
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f ./Dockerfile -t $REPO:$COMMIT ./
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
