version: '2'
services:
    opengive-app:
        image: opengive
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://opengive-mariadb:3306/opengive
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=opengive-elasticsearch:9300
        ports:
            - 8080:8080
    opengive-mariadb:
        extends:
            file: mariadb.yml
            service: opengive-mariadb
    opengive-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: opengive-elasticsearch
